#!/bin/bash

# commands
display-help() {
  cat <<'HELP'
usage: autotags [options] <command> <path>
  command: a command to run (see below)
  path:    directory to operate on (defaut: .)

Options:
  -v:  enable verbose logging
  -h:  display this help message

Commands:
  help:    display this help message
  status:  display whether or the given path is being watched or not
  watch:   monitor the given directory for changes and generate ctags
  stop:    stop monitoring the given directory
HELP
}

# options
parse-options() {
  export verbose=0
  export path=.
  OPTIND=1
  while getopts 'hv' opt; do
    case "$opt" in
      v)
        export verbose=1
        ;;
      h|?)
        display-help
        exit
        ;;
    esac
  done
  shift $((OPTIND - 1))

  export cmd=$1
  [[ "$#" -gt "1" ]] && export path=$2
}

dispatch-command() {
  local cmd=$1
  local path=$2

  case "$cmd" in
    status)
      echo 'running status'
      ;;
    watch)
      echo 'running watch'
      ;;
    stop)
      echo 'running stop'
      ;;
    help)
      display-help
      ;;
    *)
      echo "unknown command: $cmd"
      display-help
      exit 1
      ;;
  esac
}

parse-options "$@"
dispatch-command $cmd $path
echo "autocmd '$cmd' '$path' (verbose: $verbose)"
